language: rust
rust:
  - nightly
cache: cargo
before_script:
  - rustup component add rustfmt-preview
script:
  - cargo fmt -- --write-mode=diff
  - cargo build
  - cargo test
notifications:
  email: false
