language: rust
cache:
  cargo: true
  directories:
    - ${HOME}/google-cloud-sdk
sudo: false
git:
  depth: 1
notifications:
  email: false
jobs:
  fast_finish: true
  allow_failures:
    - rust: nightly
      env:
  include:
    - stage: commit
      rust: stable
    - stage: commit
      rust: nightly
    - stage: commit
      rust: nightly
      env: RUSTFMT=1
      before_script: rustup component add rustfmt-preview
      script: cargo fmt -- --write-mode=diff
    - stage: commit
      rust: nightly
      before_script: cargo install clippy --debug --force
      script: cargo clippy
    - stage: release
      sudo: required
      services: docker
      env:
        - APP=signals
      script:
        - |
          source scripts/ns.setup.profile &&
          scripts/gcloud.install.sh &&
          scripts/k8s.install.sh &&
          scripts/k8s.cluster.init.sh &&
          scripts/skaffold.install.sh &&
          PATH_TO_FILE=${TRAVIS_BUILD_DIR}/k8s/cloud-sql scripts/k8s.chart.download.sh &&
          docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD} &&
          scripts/skaffold.init.sh &&
          scripts/skaffold.run.sh
    - stage: migrate
      sudo: required
      services: docker
      script:
        - |
          source scripts/ns.setup.profile &&
          scripts/gcloud.install.sh &&
          scripts/k8s.install.sh &&
          scripts/k8s.cluster.init.sh &&
          DOCKER_IMAGE_NAME=signals-migrations DOCKER_FILE=migrations.Dockerfile scripts/docker.image.publish.sh &&
          PATH_TO_CHARTS=${TRAVIS_BUILD_DIR}/k8s/migrations-cloud-sql.yaml scripts/k8s.charts.apply.sh
    - stage: publish
      rust: stable
      before_script:
        - cargo install mdbook || true
      script:
        - |
          scripts/gcloud.install.sh &&
          source ${HOME}/google-cloud-sdk/path.bash.inc
          mdbook build docs/ --dest-dir site/book/ &&
          cargo doc --no-deps &&
          mv target/doc docs/site/rustdoc &&
          gsutil -m rm -rf gs://signals-rs.docs.netology-group.services/* &&
          gsutil -m mv -ra public-read docs/site/* gs://signals-rs.docs.netology-group.services &&
          rm -rf docs/site/book docs/site/rustdoc
script:
  - cargo build
  - cargo test
stages:
  - name: warmup
  - name: commit
  - name: test
  - name: release
    if: branch = master AND type = push
  - name: migrate
    if: (branch = master AND type = push) AND env(TRAVIS_TAG) IS present
  - name: publish
    if: branch = master AND type = push
