[package]
name = "signals-rs"
version = "0.1.0"
authors = ["Aleksey Ivanov <ialexxei@gmail.com>"]

[dependencies]
rumqtt = "0.10.1"
error-chain = "0.11.0"
serde = "1.0.27"
serde_derive = "1.0.27"
serde_json = "1.0.9"
nom = "3.2.1"
