apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
    - imageName: netologygroup/signals-rs
      workspace: .
      dockerfilePath: docker/Dockerfile
  local: {}
deploy:
  kubectl:
    manifests:
      - k8s/cloud-sql/*
