apiVersion: apps/v1
kind: Deployment
metadata:
  name: signals
  labels:
    app: signals
spec:
  replicas: 1
  selector:
    matchLabels:
      app: signals
  template:
    metadata:
      labels:
        app: signals
    spec:
      containers:
        - name: signals-rs
          image: netologygroup/signals-rs:latest
          env:
            - name: MQTT_HOST
              valueFrom:
                configMapKeyRef:
                  name: signals-configmap
                  key: mqtt-host
            - name: MQTT_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: signals-configmap
                  key: mqtt-client-id
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: cloudsql-postgresql-signals-credentials
                  key: database_url
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 500m
              memory: 1Gi
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.11
          env:
            - name: DATABASE_INSTANCE
              valueFrom:
                configMapKeyRef:
                  name: signals-configmap
                  key: database-instance
          command: [ "/cloud_sql_proxy" ]
          args: [
            "-instances=$(DATABASE_INSTANCE)",
            "-credential_file=/secrets/cloudsql/credentials.json"
          ]
          volumeMounts:
            - name: cloudsql-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
          resources:
            requests:
              cpu: 0m
              memory: 0Mi
            limits:
              cpu: 0m
              memory: 0Mi
      volumes:
        - name: cloudsql-credentials
          secret:
            secretName: cloudsql-credentials
